### ISSUE TITLE
Editing Issue labels

### ISSUE THREAD

**Issue by keremuslular** [bounswe/bounswe2020group7#11]
Determine and edit the issue tag labels and colors.

**Comment by alperendivriklioglu** [comment]
After I assessed the suggestions of my teammates and researched, I've selected the following labels to be used to classify our issues (The list is subject to change within time according to our needs):

 --Type--

Type: Bug
A problem which impairs of prevents the functions of the product.

Type: Improvement:
An improvement or enhancement to an existing feature or task.

Type: New Feature
A new feature of the product, which has yet to be developed.

Type: Task
A task that needs to be done. (For non-technical issues)

--Status--

Status: To Do
The issue has been reported and is waiting for the team to action it.

Status: In Progress
This issue is being actively worked on at the moment by the assignee.

Status: Done
Work has finished on the issue.

Status: In Review
The assignee has carried out the work needed on the issue, and it needs peer review before being considered done.

Status: Under review
A reviewer is currently assessing the work completed on the issue before considering it done.

Status: Approved
A reviewer has approved the work completed on the issue and the issue is considered done.

Status: Cancelled
Work has stopped on the issue and the issue is considered done.

Status: Rejected
A reviewer has rejected the work completed on the issue and the issue is considered done.

Status: Waiting For Response
When the issue needs a response from the instructors for further work.

Status: Help Needed
When the assignee experienced difficulties while working on the issue and needs help from the other team members.

--Priority--

Priority: Highest
This problem will block progress.

Priority: High
Serious problem that could block progress.

Priority: Medium
Has the potential to affect progress.

Priority: Low
Minor problem or easily worked around.

Priority: Lowest
Trivial problem with little or no impact on progress.
