### ISSUE TITLE
Database reset problem in every deployment

### ISSUE THREAD

**Issue by ahmetdadak** [bounswe/bounswe2020group7#177]
Database resets itself on every deployment. Is there any way to solve this issue?

**Comment by HUmutOzdemir** [comment]
This problem is about the initializing volumes on docker compose file. This feature is also needed to protect the files in the File System that is one of the most important parts of the Milestone 2. So, It is very important I think. We have to solve it as soon as possible. So, I will change its priority level.

**Comment by HUmutOzdemir** [comment]
I solved this issue by some changes on docker-compose.yaml.
