### ISSUE TITLE
Milestone 1 Report - Code structure and group process

### ISSUE THREAD

**Issue by cakmadam98** [bounswe/bounswe2020group7#191]
"The code structure and group process should be documented, for example, if each feature is a branch and what are the branches, how are pull requests used, etc."

Deadline is 29.11.2020 10:00

**Comment by BurhanAkkus** [comment]
arkadaslar bunu birlikte yapmamız gerek. Yarın akşam müsait misiniz 8-9 gibi?

**Comment by ertbulbul** [comment]
As Android team, we have taken care to use Git version-control system efficiently in order to do that we have two main branch for our android development which are called android-release, android-dev and other task specific branches. The most base branch is called android-release. The purpose of this branch is keep the project that has become deliverable in a way that will not change until the next deliverable. The second most important one is the android-dev which is the branch where we combine our simultaneous developments. According to the tasks given to us, we made the necessary implementation by opening a new branches by taking the android-dev branch as a base, and then at the end of the implementation we merged our task branch with android-dev. In fact, we were setting the names of task specific branches very well in the beginning, but due to the decreasing time and some problems we had with git, meaningless branch names appeared later, but this was a great lesson for us to use it more correctly for our ongoing development process. We tried to use the hotfix branch, but we cannot say that we use it efficiently until this milestone, but we will start using it effectively up to next milestone.

Task Specific Branches:

1- android-dev-lrpage :

It was the first branch that we  merged in android dev. Task of this branch was login page, register page and forget password page implementation. Also initial design of the bottom navigation bar is implemented on this branch. Also some UI updates for pre login page is made.

2- android-dev-profile-page :

Profile page, followers page, following page, and edit profile pages implemented. Also backend connection of these pages are implemented in this branch. 


3- android-dev-lrfpage :

Rx Kotlin is implemented in order to provide data transfer from repository class to presenter class. Also some small bug fixes are done.

4- android-dev-profile-request:

Research information request and get user request handled in this task. Also home page activity stream recycler view and its adapter is implemented.

5- android-dev-presentation

This branch was created due to the problem we encountered in merging with android-dev.

**Comment by alperendivriklioglu** [comment]
Backend Code Structure: 

 As the backend team, our choice of web application framework to use is Flask, which has given us a greater flexibility in creating our directory structure. Therefore, instead of the exact directory structure shown in the official Flask documentation, we use a modified and a Django-like version of it: we have factored our app into modules - where related functionalities are located together. (for example, "Login", "Reset Password" and "Create User" functionalities are all located in the "auth_system" folder/module.) In each module, we have "models.py", "views.py", "forms.py" and "helpers.py".
 - "models.py" contains the description of the data models to be used in that module,
 - "views.py" contains the methods for each endpoint,
 - "forms.py" contains the forms for the endpoints that receive data from the client, those forms makes it convenient to validate input data.
 - "helpers.py" contains the methods that are not the direct equivalent of the endpoints but that help them.
 
 This directory structure has streamlined our development process, as we know where we should write the code of a new feature or where a bug to be fixed is located.

 Group Process:

 We have utilized Git and its branching feature for better version control. We have a root branch named "backend-dev", and each of our team members branches from that root branch to implement the functionality that they're assigned to implement. For example, the branch named "backend-dev-registration" from "backend-dev" was created for the implementation of the RESTful API for "User" resource. As another example, "backend-dev-login" was created for the implementation of the login system.

 The list of the backend branches:
- backend-dev: The root backend branch
- backend-dev-docker-infrastructure: The branch for the implementation of the Docker infrastructure for the backend
- backend-dev-follow: The branch for the implementation of the follow system
- backend-dev-jobs/skills: The branch for the implementation of the RESTful API for "Job" and "Skill" resources
- backend-dev-login: The branch for the implementation of the login system
- backend-dev-notification: The branch for the implementation of the notification system
- backend-dev-registration: The branch for the implementation of the RESTful API for "User" resource
- backend-dev-research_info: The branch for the implementation of the research information collection system

 After a team member finishes their task and wants to push the code on their local machine to our GitHub repository, they push their code to a branch carrying the same name with the branch on their local machine. For example, after the implementation in the "backend-dev-follow" has been finished on one's local, they must push the code to "backend-dev-follow" branch of our GitHub repository. After the push is done, the team member goes to GitHub and opens a pull request for the code to be merged into "backend-dev" branch. In the pull request, the team member asks other team members to review the code and approve the request if the code is well written.
