### ISSUE TITLE
Milestone 1 Report - Evaluation of tools and managing the project

### ISSUE THREAD

**Issue by cakmadam98** [bounswe/bounswe2020group7#192]
"Evaluation of tools and managing the project. This is a lesson learned from the project development decisions made so far. Tools are for planning, IDE, frameworks, and everything. The management is the process used by the team, including how the tools are being effectively utilized. If there are some aspects that are not working out, what kind of changes are planned."

Deadline is 29.11.2020 10:00

**Comment by darktheorys** [comment]
# ANDROID
___
We have used Android Studio as our IDE; Slack, Github repository and Trello as our main processing tools which are very basic tools that should not have been forgotten while developing an android application.

We have decided to use Model-View-Presenter (MVP) architecture at the beginning of implementation and stick to it. However, while developing we have realized that it is quite old, and there are better architectures. We have decided to change the architecture of our android application from MVP to MVVM. This will take some time but we have it on our to-do list.

We have had to use some REST API interface to communicate with the backend. Therefore, our team separately made research. We have come to the decision of using Retrofit2 library as our HTTP client. We are very delighted to use it because it has a lot of documentation and resources on the internet. 

We have had to use some kind of parallel processing in order to manage time and have a responsive UI while sending requests to the server. Our team separately researched for it and we have tried to use 3 separate ways to implement it. First one is the simplest and the worst one, to synchronize threads we have used local storage and a thread that checks whether some change happened in that file. As you can see, we had to change it very fast. Second one is implementing a basic HTTPRequestListener to listen for changes in the responses. It worked really well. However, there are some libraries that implement this feature by itself called RX-Java3. We can use either of the latter two, but using the library could be better in the future.
 
We have used Git very frequently in our development. We have constructed “android-dev”, “android-release” branches as bases. Then, each task has branched from them. We have faced some merge issues, but we have believed that using MVP made our merge task easier. Using MVVM in future will make it easier in our opinion.

**Comment by oykuyilmaz1** [comment]
We delivered the report
