### ISSUE TITLE
Requirements v1.0

### ISSUE THREAD

**Issue by oykuyilmaz1** [bounswe/bounswe2020group7#23]
Here are the categories we decided in the meeting: 
https://github.com/bounswe/bounswe2020group7/wiki/Req-v1.0-Headings

Please categorize our existing requirements by 28.02.2020 23.00: 

- [x] Ahmet Dadak @ahmetdadak 

Please check them by 29.02.2020 12.00:

- [x] Umut Ozdemir @HUmutOzdemir 

- [x] Kerem Uslular @keremuslular

**Comment by ahmetdadak** [comment]
Our existing requirements are categorized [here](https://github.com/bounswe/bounswe2020group7/wiki/Req-v1.0-Headings).

**Comment by HUmutOzdemir** [comment]
I checked the Requirements Page and I made some changes.
* For the requirements which are valid for only registered users, I add "a registered user" instead of "users".
* Some of the requirements are not detailed enough I made them detailed and I added new things to glossary for them.
* Some requirements in the user part are placed under system requirements and vice versa.
* I add a new heading toı the system requirements "Profile Page".
* The following requirements aren't detailed. I delete them for now, we can add detailed versions of them:
1. There should be tags of contents to improve the functionality of the search engine.
2. The profile page shall provide information about any other related content.
* There are requirements about the "Saved" section. We have to ask it to our customer, so I deleted its requirement and its part in the glossary.

**Comment by alperendivriklioglu** [comment]
- [ ] @HUmutOzdemir 

- [ ] @keremuslular 

- [ ] @Hryurt 

https://github.com/bounswe/bounswe2020group7/wiki/Meeting-%235-(05.03.2020)#4-action-items

**Comment by HUmutOzdemir** [comment]
We edited the [Requirements document](https://github.com/bounswe/bounswe2020group7/wiki/Project-Requirements). Please check the document and write comments if there is any mistake.

- [ ] Meltem Arslan
- [ ] Ertuğrul Bülbül
- [ ] Hasan Ramazan Yurt
- [ ] Burak Ömür
- [ ] Mehmet Temizel
- [ ] Öykü Yılmaz
- [ ] Alperen Divriklioğlu

**Comment by keremuslular** [comment]
We reviewed all the requirements and re-classified and removed some of them.
You can reach the final product [here](https://github.com/bounswe/bounswe2020group7/wiki/Project-Requirements)

Please review the changes we made on the page and give feedback if you detect any mistakes.

- [ ] Alperen Divriklioğlu @alperendivriklioglu 

- [ ] Burak Ömür @darktheorys 

- [ ] Ertuğrul Bülbül @ertbulbul 

- [ ] Hasan Ramazan Yurt @Hryurt 

- [ ] Mehmet Temizel @MEHMETTEMIZEL 

- [ ] Meltem Arslan @meltemarsl 

- [ ] Öykü Yılmaz @oykuyilmaz1

**Comment by MEHMETTEMIZEL** [comment]
The requirements looked good but we should think these requirements(1.1.5.3 and 1.2.6.3) again if the users don't have the Google Scholar & ResearchGate accounts.

**Comment by HUmutOzdemir** [comment]
> The requirements looked good but we should think these requirements(1.1.5.3 and 1.2.6.3) again if the users don't have the Google Scholar & ResearchGate accounts.

@MEHMETTEMIZEL 
* I think there isn’t any problem in 1.1.5.3. Because it says “shall be able to” so users can choose not to link their account.
* For 1.2.6.3, you are right. So, I changed this requirement as follows:
**1.2.6.3 The profile page should be fetched from the users' Google Scholar or ResearchGate account, if Google Scholar or ResearchGate account is provided to the system.**

**Comment by MEHMETTEMIZEL** [comment]
> > The requirements looked good but we should think these requirements(1.1.5.3 and 1.2.6.3) again if the users don't have the Google Scholar & ResearchGate accounts.
> 
> @MEHMETTEMIZEL
> 
> * I think there isn’t any problem in 1.1.5.3. Because it says “shall be able to” so users can choose not to link their account.
> * For 1.2.6.3, you are right. So, I changed this requirement as follows:
>   **1.2.6.3 The profile page should be fetched from the users' Google Scholar or ResearchGate account, if Google Scholar or ResearchGate account is provided to the system.**

> * I actually want to mention that point, thank you.
