### ISSUE TITLE
Tag label ideas

### ISSUE THREAD

**Issue by keremuslular** [bounswe/bounswe2020group7#6]
Find ideas about the label tags and sends their ideas on Slack.

**Comment by MEHMETTEMIZEL** [comment]
I have found label tags from a group in last years. These tags are very useful. I asked my friend and he said these label tags were also used in a software development company.

**Comment by oykuyilmaz1** [comment]
Status: Pending
Status: On hold
Status: Aborted
Status: Fix in progress
Status: Work in progress
Status: Improvement needed
Status: Test needed
Status : Resolved
Status: Review needed


Wiki-Related
Typo fix

**Comment by ahmetdadak** [comment]
Type: Bug
Type: Discussion
Type: Needs Investigation

Some labels that may be useful

**Comment by HUmutOzdemir** [comment]
We can add a `Help Needed` tag which can be used to ask for help on a code piece. Also labels like `Effort: Few Days`, `Effort: Few Hours`, `Effort: Few Weeks` can be added which define the difficulty of the issue.

**Comment by meltemarsl** [comment]
Status: Waiting for response    (If we need a response from the assistant etc. to continue)
Type(?): Urgent

**Comment by alperendivriklioglu** [comment]
--Type--

Bug: A problem which impairs of prevents the functions of the product.
Improvement: An improvement or enhancement to an existing feature or task.
New Feature: A new feature of the product, which has yet to be developed.
Task: A task that needs to be done. (For non-technical issues)

--Status--

In Progress: This issue is being actively worked on at the moment by the assignee.
Done: Work has finished on the issue.
To Do: The issue has been reported and is waiting for the team to action it.
In Review: The assignee has carried out the work needed on the issue, and it needs peer review before being considered done.
Under review: A reviewer is currently assessing the work completed on the issue before considering it done.
Approved: A reviewer has approved the work completed on the issue and the issue is considered done.
Cancelled: Work has stopped on the issue and the issue is considered done.
Rejected: A reviewer has rejected the work completed on the issue and the issue is considered done.

--Priority--

Highest: This problem will block progress.
High: Serious problem that could block progress.
Medium: Has the potential to affect progress.
Low: Minor problem or easily worked around.
Lowest: Trivial problem with little or no impact on progress.
