### ISSUE TITLE
Practice App - Frontend 

### ISSUE THREAD

**Issue by MEHMETTEMIZEL** [bounswe/bounswe2020group7#64]
Deadline @20.05.2020

**Comment by ahmetdadak** [comment]
The frontend of our-app can be found [practice-app-frontend](https://github.com/bounswe/bounswe2020group7/tree/practice-app-frontend) branch. Since, we encountered a push problem while pushing the last version, we created new branch [practice-app-deploy](https://github.com/bounswe/bounswe2020group7/tree/practice-app-deploy). The last version can be found this branch.
